
package by.egar.servertime.soap;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeWebService", targetNamespace = "http://soap.servertime.egar.by/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface TimeWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.servertime.egar.by/TimeWebService/getTimeRequest", output = "http://soap.servertime.egar.by/TimeWebService/getTimeResponse")
    String getTime();

}
